[package]
name = "frontend-cli"
version = "0.1.0"
authors = ["Ojos Project"]
edition = "2021"
description = "A CLI tool to help create frontend-related tasks."
repository = "https://github.com/ojosproject/frontend-cli"
license = "GPL-3.0-only"


[dependencies]
